language: objective-c
osx_image: xcode11.4

branches:
  only:
  - master

env:
  global:
  - NODE_VERSION=stable

install:
- brew tap wix/brew
- brew install applesimutils
- brew install yarn
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
- export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- nvm alias default $NODE_VERSION
- yarn
- yarn global add react-native-cli
- yarn global add detox-cli
# - npm install -g react-native-cli
# - npm install -g detox-cli

script:

# -  detox build --configuration ios.sim.release
# - detox test --configuration ios.sim.release --cleanup
- travis_wait 20 yarn ci:build:e2e
- yarn ci:test:e2e