language: objective-c
os: osx
osx_image: xcode11.4

branches:
  only:
  - master

env:
  global:
  - NODE_VERSION=stable

install:
  - bash ./travisci/ios-install.sh

script:
  - bash ./travisci/ios-script.sh
